---

- name: Install NFS client
  apt:
    name: "nfs-common"
    state: present
  tags:
    - grafana
    - logging

- name: Ensure EFS volume mountpoint exists
  file:
    path: "{{ grafana_efs_mountpoint }}"
    state: directory
  tags:
    - grafana
    - logging

- name: Mount EFS target for persistent app storage
  mount:
    name: "{{ grafana_efs_mountpoint }}"
    src: "{{ ansible_ec2_placement_availability_zone }}.{{ grafana_filesystem_id }}.efs.{{ ec2_region }}.amazonaws.com:/"
    fstype: nfs4
    state: mounted
  tags:
    - grafana
    - logging

- name: Ensure Grafana directories exist
  file:
    path: "{{ grafana_efs_mountpoint }}/{{ item }}"
    state: directory
  with_items:
    - "data"
    - "mysql"
  tags:
    - grafana
    - logging

- name: Run MySQL for grafana docker instance
  docker_container:
    name: mysql-grafana
    image: mysql:{{ grafana_mysql_version }}
    state: started
    pull: true 
    volumes:
      - "{{ grafana_efs_mountpoint }}/mysql:/var/lib/mysql"
    env:
      MYSQL_DATABASE: "grafana"
      MYSQL_USER: "{{ grafana_mysql_user }}"
      MYSQL_PASSWORD: "{{ grafana_mysql_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart_policy: always
  tags:
    - grafana
    - logging

- name: Run Grafana docker instance
  docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    state: started 
    pull: true 
    ports:
      - "3000:3000"
    volumes:
      - "{{ grafana_efs_mountpoint }}/data:/var/lib/grafana"
    links:
      - "mysql-grafana"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_DATABASE_TYPE: "mysql"
      GF_DATABASE_HOST: "mysql-grafana:3306"
      GF_DATABASE_NAME: "grafana"
      GF_DATABASE_USER: "{{ grafana_mysql_user }}"
      GF_DATABASE_PASSWORD: "{{ grafana_mysql_password }}"
    restart_policy: always
  tags:
    - grafana
    - logging

- name: Setup grafana consul service and check definitions
  template:
    src: consul.json.j2
    dest: /etc/consul.d/grafana.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - grafana
    - logging
    - consul
