---

- hosts: all
  become: true
  roles:
    - oefenweb.postfix
    - docker
    - common
    - consul
    - jnv.unattended-upgrades
    - security

- hosts: admin
  become: true
  roles:
    - admin
    - jenkins
    - docker-registry
    - grafana
  tags:
    - admin
    - jenkins
    - grafana
  vars:
    jenkins_efs_mountpoint: '/opt/jenkins'
    jenkins_filesystem_id: 'fs-1766af5e'

- hosts: jenkins-public
  become: true
  roles:
    - jenkins
  tags:
    - jenkins
  vars:
    jenkins_efs_mountpoint: '/opt/jenkins'
    jenkins_filesystem_id: 'fs-3f1dd776'

- hosts: mesos-master
  tasks: []
  tags:
    - always

- hosts: mesos-slave
  tasks: []
  tags:
    - always

- hosts: storage
  tasks: []
  tags:
    - always

- hosts: sensu
  become: true
  roles:
    - sensu
  tags:
    - sensu-master
    - monitoring

- hosts: logstash
  become: true
  roles:
    - logstash
  tags:
    - logstash
    - logging

- hosts: openvpn
  become: true
  roles:
    - openvpn-firewall
    - Stouts.openvpn
  tags:
    - openvpn

- hosts: mesos-master
  become: true
  roles:
    - mesos-common
    - mesos-master
  tags:
    - mesos-master

- hosts: mesos-slave
  become: true
  roles:
    - mesos-common
    - mesos-slave
    - metadata-proxy
  tags:
    - mesos-slave
